export const AUTHENTICATION = {
    LOGIN: "AUTHENTICATION.LOGIN",
    LOGOUT: "AUTHENTICATION.LOGOUT",
    UPDATE_ACCESS: "AUTHENTICATION.UPDATE_ACCESS"
}

export const ROLES = {
    STUDENT: 'Student',
    TEACHER: 'Teacher'
}
